services:
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    volumes:
      - ${PWD}/observability/prometheus:/etc/prometheus
      - ${PWD}/${ENVIRONMENT}/prometheus:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    user: root
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.2.2
    container_name: grafana
    volumes:
      - ${PWD}/observability/grafana/provisioning:/etc/grafana/provisioning
      - ${PWD}/${ENVIRONMENT}/grafana/data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    user: ${USER}
    env_file:
      - ${PWD}/${ENVIRONMENT}/grafana/.env_grafana
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
